### ISSUE TITLE
Not working and no error is preset

### ISSUE THREAD

**Issue by walmon** [harouny/NLog.Extensions.AzureTableStorage#27]
Followed the tutorial on how to get it working, no error is launch but nothing registered.
I even created the table before hand.

Any idea how to see or enable logs?

**Comment by walmon** [comment]
Hi, I found internal logs, Im copying the connection string right from azure but this is being logged

Parameter ConnectionStringKey not supported on AzureTableStorageTarget

**Comment by ellistev** [comment]
How did you solve this issue?  I'm having the exact same problem and the Internet has no answers for me...

**Comment by WillPwn4Food** [comment]
Same here, I copied same code the worked fine in another project, but I get this error now!

**Comment by vtkachenko** [comment]
The same problem happens with me. 

> System.NotSupportedException: Parameter ConnectionStringKey not supported on AzureTableStorageTarget

nlog.config target:

`<target` xsi:type="AzureTableStorage"
                name="azuretables"
                ConnectionStringKey="sampleAzureTableStorage" 
                TableName="sampleLogs"  />

Anyone got a solution? It's core functionality - and it should work, even if product is not supported anymore :)

**Comment by harouny** [comment]
Hey, make you you have installed the right package...check issue #35

**Comment by vtkachenko** [comment]
Thanks for the answer! I was inattentive enough to install the wrong package... Maybe, it would be good to announce fork's existence in Readme in order to avoid similar situations.

But when I installed the [right one](https://www.nuget.org/packages/AzureTableStorageNLogTarget/) - I got another error: 

> Error Error initializing target 'AzureTableStorage Target[azuretables]'. Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: connectionString
   at Microsoft.WindowsAzure.Storage.CloudStorageAccount.Parse(String connectionString)
   at NLog.Extensions.AzureTableStorage.TableStorageManager..ctor(ConfigManager configManager, String tableName)
   at NLog.Extensions.AzureTableStorage.AzureTableStorageTarget.InitializeTarget()
   at NLog.Targets.Target.Initialize(LoggingConfiguration configuration)

Connection string is initialized in **web.config** of my ASP.NET Core project:'

`<configuration>
  <appSettings>
    <add key="AzureTableStorage" value="DefaultEndpointsProtocol=https;AccountName=XXX;AccountKey=XXX;" />
  </appSettings>
  ...
</configuration>`

I saw issue #20 - but I have set up connection string according to the requirements, I guess.
